In [2]:
# Importing necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

#### 2. LIST MANIPULATION

In [3]:
list_a = [3, 4, 6, 10, 39, 87, 12, 54]
list_a = np.array(list_a)
# Maximum value of the list
a_max = np.max(list_a)
print('The maximum value in the list is:', a_max)
# Minimum value of the list
a_min = np.min(list_a)
print('\n')
print('The maximum value in the list is:', a_min)
# Sum of all the values in the list
a_sum = np.sum(list_a)
print('\n')
print('The sum of the list is:', a_sum)


# Sorting the list
sorted_list = np.sort(list_a)
print('\n')
print('The sorted list is:', sorted_list)


# A for loop
for  i in range(0, len(list_a)):
    print(list_a[i])

The maximum value in the list is: 87


The maximum value in the list is: 3


The sum of the list is: 215


The sorted list is: [ 3  4  6 10 12 39 54 87]
3
4
6
10
39
87
12
54


3. PRIME NUMBER AND FACTOR

In [6]:
def prime_number(n):
    if n == 1:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

# Example
print('\n')
integers = [3, 2, 7, 11, 15, 18, 9 , 13]

for n in integers:
    print(prime_number(n))

# prime_number(5)
print('\n')
print('The prime numbers between 1 and 100 are: ')
for i in range(1, 100):
    if prime_number(i):
        print(i, end=' ')





True
True
True
True
False
False
False
True


The prime numbers between 1 and 100 are: 
2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 

Prime Numbers below 1000

In [8]:
def prime_numbers_custom(n):
    """Return a list of all prime numbers below n."""
    if n < 2:
        return []
    
    primes = []
    for num in range(2, n):  # Starting from 2 to n-1
        is_prime = True
        for i in range(2, int(num**0.5) + 1):  # Check divisibility up to sqrt(num)
            if num % i == 0:
                is_prime = False
                break
        if is_prime:
            primes.append(num)
    
    return primes

# For prime numbers below 1000 
print(prime_numbers_custom(1000))


[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997]


4. Define a function to output a 3D (n×3×3) numpy array, where n is the input value (argument) of the function to control the length of the array, and data is the input value that determines what kind of data it contains

In [9]:
def generate_3d_array(n, data='zero'):
    if data == 'zero':
        return np.zeros((n, 3, 3))
    elif data == 'random':
        return np.random.randint(1, 101, (n, 3, 3))
    else:
        raise ValueError("Invalid data type. Use 'zero' or 'random'.")

(b) Call the function for n=10 and populate the array with zeroes

In [10]:
array_zeros = generate_3d_array(10, data='zero')
print("Array with zeroes:\n", array_zeros)

Array with zeroes:
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


Call the function for n=5 and populate the array with random numbers between 1 and 100

In [11]:
array_random = generate_3d_array(5, data='random')
print("Array with random numbers:\n", array_random)

Array with random numbers:
 [[[57 73 85]
  [94 82 13]
  [80 44 91]]

 [[29 98 14]
  [87 74 33]
  [41 36 92]]

 [[85 40 57]
  [34 19  4]
  [47 16 68]]

 [[82 48  4]
  [15 81 12]
  [18 12 91]]

 [[46 21  1]
  [78 22 73]
  [79 13 89]]]


5. Solving the set of equations using linear algebra and numpy

In [12]:
# Defining  the coefficients as  matrix A
A = np.array([[3, 4, -5], 
              [0, 5, 1], 
              [1, 3, 6]])

# Defining the right-hand side values as matrix B
B = np.array([10, 8, -5])

# Solving for x (a, b, c)
solution = np.linalg.solve(A, B)

# Print the solution
a, b, c = solution
print(f"a = {a}, b = {b}, c = {c}")


a = -1.7, b = 1.9, c = -1.5


6. Given an expression:

 y = 0.1x^3-x^2+5

 (a) Plot the function in the range of x from -5 to 5
 (b) Find the maximum and minimum value of this function and add them with points and labels on the same figure


In [13]:
# Defining the function for plotting

def function(x):
    return 0.1*x**3 - x**2 + 5


# Defining the range of x values
x = np.arange(-5, 6, 1)

y = function(x)
print(y)

# Maximum value of y
y_max = np.max(y)

# Minimum value of y
y_min = np.min(y)

x_max = x[np.argmax(y)]  # x-value of global maximum
x_min = x[np.argmin(y)]  # x-value of global minimum




# Plot min points
plt.plot(x, y, color='green', label='y = 0.1*x**3 - x**2 +5', zorder=2)

# Plotting  max point
plt.scatter(x_max, y_max, color='red', label='Maxima', zorder=3)

# Plotting min point
plt.scatter(x_min, y_min, color='blue', label='Minima', zorder=3)
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt
plt.title('Graph of y = 0.1*x**3 - x**2 +5 against x')
plt.legend(loc='best');


[-32.5 -17.4  -6.7   0.2   3.9   5.    4.1   1.8  -1.3  -4.6  -7.5]
